#ifndef __MYVST3DEF_H__
#define __MYVST3DEF_H__

// parameter tag identifiers
enum ParameterTags {
	// control
	PARAMETER_COMPRESSION_RATIO_ML,
	PARAMETER_COMPRESSION_RATIO_SR,
	PARAMETER_THRESHOLD_ML,
	PARAMETER_THRESHOLD_SR,
	PARAMETER_MAKEUP_ML,
	PARAMETER_MAKEUP_SR,
	PARAMETER_ATTACK_ML,
	PARAMETER_ATTACK_SR,
	PARAMETER_RELEASE_ML,
	PARAMETER_RELEASE_SR,
	PARAMETER_KNEE_WIDTH_ML,
	PARAMETER_KNEE_WIDTH_SR,
	PARAMETER_SMOOTHNESS_ML,
	PARAMETER_SMOOTHNESS_SR,
	PARAMETER_TRIGGER_SIGNAL_RATIO_ML,
	PARAMETER_TRIGGER_SIGNAL_RATIO_SR,
	PARAMETER_WET_RATIO_ML,
	PARAMETER_WET_RATIO_SR,
	PARAMETER_CLIPPING_HARDNESS_ML,
	PARAMETER_CLIPPING_HARDNESS_SR,
	PARAMETER_CLIPPING_THRESHOLD_ML,
	PARAMETER_CLIPPING_THRESHOLD_SR,

	PARAMETER_CLIPPING_ENABLED_ML,
	PARAMETER_CLIPPING_ENABLED_SR,
	PARAMETER_CLIPPING_LEVEL_ML,
	PARAMETER_CLIPPING_LEVEL_SR,
	PARAMETER_MID_SIDE_MODE_ENABLED,
	PARAMETER_CONTROL_LINK_ENABLED,
	PARAMETER_BYPASSED_ML,
	PARAMETER_BYPASSED_SR,
	PARAMETER_MUTED_ML,
	PARAMETER_MUTED_SR,

	// display
	PARAMETER_OUTPUT_LEVEL_ML,
	PARAMETER_OUTPUT_LEVEL_SR,
	PARAMETER_REDUCTION_LEVEL_ML,
	PARAMETER_REDUCTION_LEVEL_SR,
};



#endif